---
abstract: 'Perl bindings to the portable FFI library (libffi)'
author:
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  Env: '0'
  ExtUtils::CBuilder: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Math::BigInt: '0'
  POSIX: '0'
  Test::More: '0'
  Text::ParseWords: '0'
  base: '0'
  bigint: '0'
  lib: '0'
  perl: '5.010'
configure_requires:
  Devel::CheckLib: '0'
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Raw
recommends:
  Math::Int64: '0'
requires:
  XSLoader: '0'
  overload: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/ghedo/p5-FFI-Raw/issues
  homepage: http://metacpan.org/release/FFI-Raw/
  repository: git://github.com/ghedo/p5-FFI-Raw.git
version: '0.32'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Filter/@GitHub/GitHub::Meta'
      version: '0.36'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/@GitHub/GitHub::Update'
      version: '0.36'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: 0.01
          version_by_branch: '0'
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Filter/Git::NextVersion'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@Filter/PodVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Filter/Test::Compile'
      version: '2.040'
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Filter/Test::CheckManifest'
      version: '0.04'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Filter/Git::Commit'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.32
          tag_format: v%v
          tag_message: '%N %v'
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Filter/Git::Tag'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Filter/Git::Push'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Filter/Clean'
      version: '0.07'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: Recommends
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: configure
          type: requires
      name: ConfigureRequires
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: configure
          type: recommends
      name: ConfigureRecommends
      version: '5.019'
    -
      class: inc::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: MakeMaker
      version: ~
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.019'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.019'
